name: Projeto de DataOps

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.9.12'
    - name: install python packages
      run:
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests
          pip install pandas
          pip install sqlalchemy
          pip install pymysql
          pip install google-auth
          pip install google-cloud-storage

    - name: execute py script  
      run: 
            python scrapping.py